BankOfCyprusUK.Web/Models/SearchResultViewModel.cs
using System.Collections.Generic;
using Umbraco.Core.Models;

namespace BankOfCyprusUK.Web.Models
{
	public class SearchResultViewModel
	{
		public IEnumerable<IPublishedContent> Results { get; set; }
		public string Query { get; set; }
	}

}

BankOfCyprusUK.Web/Controllers/MainSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BankOfCyprus.OverdraftCalculator.Models;
using BankOfCyprusUK.Web.Code;
using BankOfCyprusUK.Web.Models;
using Umbraco.Web;
using Umbraco.Web.PublishedContentModels;

namespace BankOfCyprusUK.Web.Controllers    
{
	public class MainSurfaceController : Controller
	{
        private ICalculatorService CalculatorService { get; set; } = new CalculatorService();
		private UmbracoHelper Umbraco = new UmbracoHelper(UmbracoContext.Current);

		public PartialViewResult RenderTeamMembers(string teamName, string memberName, int sectionNode)
		{
			var settings = Umbraco.TypedContentAtRoot().First(n => n.DocumentTypeAlias == "settings");
			var teamNode = settings.FirstChild<TeamFolder>();
			var section = teamNode.DescendantsOrSelf<TeamSection>().Single(n => n.Id == sectionNode);

			var teams = teamName == "All"
				? section.Teams.Select(n => new Team(n)).ToList()
				: teamNode.DescendantsOrSelf<Team>().Where(n => n.Name == teamName).ToList();

			var members = teams.SelectMany(n => n.Members.Select(m => new TeamMember(m)));
			if (memberName != "All") members = new List<TeamMember> {members.First(n => n.GetKey() == new Guid(memberName))};
			
			var model = new TeamMembersViewModel
			{
				Team = teams.Count== 1 ? teams[0] : null,
				Members = members.ToList()
			};

			return PartialView(model);
		}

		[HttpPost]
		public JsonResult GetTeamMembers(string teamName, int sectionNode)
		{
			var settings = Umbraco.TypedContentAtRoot().First(n => n.DocumentTypeAlias == "settings");
			var teamNode = settings.FirstChild<TeamFolder>();
			var section = teamNode.DescendantsOrSelf<TeamSection>().Single(n => n.Id == sectionNode);

			var teams = teamName == "All"
				? section.Teams.Select(n => new Team(n)).ToList()
				: teamNode.DescendantsOrSelf<Team>().Where(n => n.Name == teamName).ToList();

			//var teamIds = teams.Select(n => n.Id);

			var members = teams.SelectMany(n => n.Members.Select(m => new TeamMember(m)));

			return Json(members.Select(n => new
			{
				n.Name,
				Key = n.GetKey()
			}), JsonRequestBehavior.AllowGet);
		}

		[HttpPost]
		public JsonResult GetRatesTableNamesByCategory(string categoryName)
		{
			var settings = new Settings(Umbraco.TypedContentAtRoot().First(n => n.DocumentTypeAlias == "settings"));
			var rates = settings.Descendants<RatesTable>().Select(n => new RatesTable(n)).ToList();
			var names = rates.Where(n => n.Type == categoryName).ToList();

			return Json(names.Select(n => n.Name), JsonRequestBehavior.AllowGet);
		}

		[HttpPost]
		public ActionResult RenderRatesTable(string name, string category, bool isExchange)
		{
			var settings = new Settings(Umbraco.TypedContentAtRoot().First(n => n.DocumentTypeAlias == "settings"));
			var rates = settings.Descendants<RatesTable>().Select(n => new RatesTable(n)).ToList();
			var cats = isExchange ? new List<string> { "Foreign Exchange" } : rates.Where(n => n.Type != "Foreign Exchange").Select(n => n.Type).ToList(); 

			IList<string> names;

			if (name != "All" && category != "All")
			{
				names = new List<string> {name};
			}
			else if (name == "All" && category == "All")
			{

				names = rates.Where(n => cats.Contains(n.Type)).Select(n => n.Name).ToList();
			}
			else if (name == "All" && ! isExchange)
			{
				names = rates.Where(n => n.Type == category).Select(n => n.Name).ToList();
			}
			else if (name == "All" && isExchange)
			{
				names = rates.Where(n => cats.Contains(n.Type)).Select(n => n.Name).ToList();
			}
			else
			{
				names = new List<string>();
			}


			var result = rates.Where(n => names.Contains(n.Name)).Select(n => new RatesTable(n)).ToList();

			return PartialView(result);
		}

        public ActionResult RenderOverdraftCalculatorResults()
        {
            var viewModel = new OverdraftCalculatorResultViewModel
            {
                ArrangedOverdraftAmount = 0,
                UnArrangedOverdraftCharge = 0,
                ChargedArrangeOverdraftInterestEAR = 0,
                CostOfBorrowing = 0,
                NumberOfDays = 0
            };

            return PartialView("OverdraftCalculator/Results", viewModel);
        }

		/// <summary>
		/// This method is for the original overdraft calculator developed in the Overdraft section of the website.
		/// </summary>
		public ActionResult CalculateOverdraft(int arrangedOverdraft, int amountOverdrawn, int numberOfDays)
        {
            var overdraftCalculatorNode = Umbraco.TypedContent(Constants.OverdraftCalculatorNodeId);

            var baseRate = CalculatorService.GetBaseRate(overdraftCalculatorNode);
            var authRate = CalculatorService.GetAuthorisedRate(overdraftCalculatorNode);
            var unAuthRate = CalculatorService.GetUnauthorisedRate(overdraftCalculatorNode);

            var model = CalculatorService.GetResults(arrangedOverdraft, amountOverdrawn, numberOfDays, baseRate, authRate, unAuthRate);
            return PartialView("OverdraftCalculator/Results", model);
        }

		/// <summary>
		/// This method is for seperate rates in April 2020 so goes to a different content node in the backoffice to get different values for the rates.
		/// </summary>
		public ActionResult CalculateOverdraftApril(int arrangedOverdraft, int amountOverdrawn, int numberOfDays)
		{
			var overdraftCalculatorNode = Umbraco.TypedContent(Constants.OverdraftCalculatorAprilNodeId);

			var baseRate = CalculatorService.GetBaseRate(overdraftCalculatorNode);
			var authRate = CalculatorService.GetAuthorisedRate(overdraftCalculatorNode);
			var unAuthRate = CalculatorService.GetUnauthorisedRate(overdraftCalculatorNode);

			OverdraftCalculatorResultViewModel model = CalculatorService.GetResults(arrangedOverdraft, amountOverdrawn, numberOfDays, baseRate, authRate, unAuthRate);
			return PartialView("OverdraftCalculator/Results", model);
		}

	}
}

BankOfCyprusUK.Web/Controllers/SearchResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BankOfCyprusUK.Web.Models;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using Umbraco.Web.PublishedContentModels;

namespace BankOfCyprusUK.Web.Controllers
{
	public class SearchResultsController : RenderMvcController
	{
		// GET: StandardPage
		[HttpPost]
		public ActionResult SearchResults(SearchRenderModel model)
		{
			//var search = ExamineManager.Instance.SearchProviderCollection["ExternalSearcher"];
			//var query = model.Query.Replace(" ", "+");
			//var criteria = search.CreateSearchCriteria(BooleanOperation.Or);
			//var compiled = criteria.Field("nodeName", query).Or().Field("title", query).Or().Field("content", query).Or().Field("tagline", query).Compile();
			//var results = search.Search(compiled);

			//results = search.Search(model.Query, true);
			if (model.Query == null) model.Query = "";

			var list = Umbraco.TypedSearch(model.Query);

			var result = new SearchResultViewModel
			{
				Query = model.Query,
				Results = list
			};


			Session["Results"] = result;
			return base.Index(model);
		}
	}
}

BankOfCyprusUK.Web/Views/Card.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Card>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = null;
}
@functions{
    private string GetStyle()
    {
        var className = "card";

        if (string.IsNullOrEmpty(Model.Content.BackgroundColour))
        {
            return className;
        }

        if (Model.Content.BackgroundColour == "Grey")
        {
            className += " grey";
        }
        else if (Model.Content.BackgroundColour == "White")
        {
            className += " white";
        }
        return className;
    }

    private string GetBodyStyle()
    {
        var className = "card-body";

        if (string.IsNullOrEmpty(Model.Content.TextAlign))
        {
            return className;
        }

        if (Model.Content.TextAlign == "Left")
        {
            className += " text-left";
        }
        else if (Model.Content.TextAlign == "Centre")
        {
            className += " text-center";
        }
        else if (Model.Content.TextAlign == "Right")
        {
            className += " text-right";
        }
        return className;
    }

    private string GetLinkStyle()
    {
        var className = "";

        if (string.IsNullOrEmpty(Model.Content.LinkStyle))
        {
            return className;
        }

        if (Model.Content.LinkStyle == "Button")
        {
            className += "button blue";
        }

        return className;
    }

    private bool HasLinkStyle()
    {
        if (Model.Content.LinkStyle == "Button")
        {
            return true;
        }

        return false;
    }

    private string GetTarget(Umbraco.Web.Models.RelatedLink link)
    {
        var defaultTarget = "_self";
        if (link == null)
        {
            return defaultTarget;
        }
        if (link.NewWindow)
        {
            return "_blank";
        }
        return defaultTarget;
    }

    private string GetImageStyle()
    {
        var css = "image";

        if (Model.Content.IsIcon)
        {
            css += " icon";
        }
        return css;
    }
}


<div class="@GetStyle()">
    @if (Model.Content.Image != null)
    {
        <div class="@GetImageStyle()" style="background-image:url('@Model.Content.Image.Url')"></div>
    }
    <div class="@GetBodyStyle()">
        @if (!string.IsNullOrEmpty(Model.Content.Title))
        {
            <h2 class="card-title">@Model.Content.Title</h2>
        }
        @if (Model.Content.Details != null)
        {
            <div class="card-text">@Html.Raw(Model.Content.Details)</div>
        }
        @if (Model.Content.Link != null && Model.Content.Link.Any())
        {
            var link = Model.Content.Link.First();
            <a href="@link.Link" target="@GetTarget(link)" class="@GetLinkStyle()">
                @link.Caption
                @if (!HasLinkStyle())
                {
                    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                }
            </a>
        }
    </div>
</div>

BankOfCyprusUK.Web/Views/CardSection.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.CardSection>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = null;
}

<div class="row">
    @if (Model.Content.Children.Where(x => x.DocumentTypeAlias == "card").Any())
    {
        var children = Model.Content.Children.Where(x => x.DocumentTypeAlias == "card");
        foreach (var element in children)
        {
            var maxCols = 12;
            var minCols = 3;
            var targetCols = maxCols / children.Count();
            if (targetCols < minCols)
            {
                targetCols = minCols;
            }
            var style = string.Format("col-md-{0}", targetCols);
            <div class="col-sm-6 @style">
                @MvcHtmlString.Create(library.RenderTemplate(element.Id))
            </div>
        }
    }
</div>

BankOfCyprusUK.Web/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;

@if (!string.IsNullOrEmpty(Model.Content.TagLine))
{
    <div class="tagline blue">
        <div class="container-fluid">
            <p>
                @Model.Content.TagLine
            </p>
        </div>
    </div>
}
@if (Model.Content.PageHeader.Any())
{
    @MvcHtmlString.Create(library.RenderTemplate(Model.Content.PageHeader.First().Id))
}

@if (Model.Content.Alerts.Any())
{
    @Html.Partial("/Views/Partials/Alerts.cshtml", Model.Content.Alerts.Select(n => new Alert(n)).ToList())
}

@if (Model.Content.Children.Any())
{
    var contentNode = Model.Content.Children.FirstOrDefault(x => x.DocumentTypeAlias == "pageContent");
    if (contentNode != null && contentNode.Children.Any())
    {
        foreach (var element in contentNode.Children)
        {
            @MvcHtmlString.Create(library.RenderTemplate(element.Id));
        }
    }
}

BankOfCyprusUK.Web/Views/MeetTheTeam.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.MeetTheTeam>
@using BankOfCyprusUK.Web.Models
@using ContentModels = Umbraco.Web.PublishedContentModels;

@Html.Partial("/Views/Partials/SectionNavigation.cshtml", null)


@if (Model.Content.DisplayTagLine)
{
    var homepage = Umbraco.TypedContentAtRoot().FirstOrDefault(x => x.DocumentTypeAlias == "homePage");
    var homePageTagLine = string.Empty;
    if (homepage != null)
    {
        homePageTagLine = homepage.GetPropertyValue<string>("tagLine");
    }
    var tagLine = !string.IsNullOrEmpty(Model.Content.TagLine) ? Model.Content.TagLine : homePageTagLine;
    <div class="tagline blue">
        <div class="container-fluid">
            <p>
                @tagLine
            </p>
        </div>
    </div>
}

@{
    var teams = new List<Team>();
    var model = new TeamMembersViewModel();

    if (Model.Content.TeamSection != null)
    {
        var settings = Umbraco.TypedContentAtRoot().First(n => n.DocumentTypeAlias == "settings");
        var teamNode = settings.FirstChild<TeamFolder>();

        var sectionNode = new TeamSection(Model.Content.TeamSection);

        var teamIds = sectionNode.Teams.Select(n => n.Id);



        foreach (var teamId in teamIds)
        {
            teams.Add(teamNode.DescendantsOrSelf<Team>().Single(n => n.Id == teamId));
        }

        Team team;
        IList<TeamMember> members;
        if (sectionNode.DefaultTeam.Any())
        {
            team = new Team(sectionNode.DefaultTeam.First());
            members = team.Members.Select(m => new TeamMember(m)).ToList();
        }
        else
        {
            team = null;
            members = teams.SelectMany(n => n.Members.Select(m => new TeamMember(m))).ToList();
        }

        model.Team = team;
        model.Members = members;

    }
}

<section class="page-header">
    <div class="container-fluid">
        <h1><span>Cynergy Bank</span>Meet the Team</h1>
    </div>
</section>

<section class="meet-the-team content-full-width">
    <div class="container-fluid">

        <div class="content">
            <form>
                <div class="row">
                    <div class="col-sm-6">
                        <label for="form-type">Filter by Team</label>
                        <select id="form-type">
                            <option value="All">All</option>
                            @foreach (var item in teams)
                            {
                                <option value="@item.Name" @(model.Team != null && item.Id == model.Team.Id ? "selected" : "")>@(item.Name)</option>
                            }

                            @*<option value="Business" @(section.ToLower() == "business" ? "selected" : "")>Business</option>
                                <option value="International" @(section.ToLower() == "international" ? "selected" : "")>International Banking</option>
                                <option value="Mortgage Intermediaries" @(section.ToLower() == "mortgage intermediaries" ? "selected" : "")>Mortgage Intermediaries</option>
                                <option value="Personal" @(section.ToLower() == "personal" ? "selected" : "")>Personal</option>
                                <option value="Property Brokers" @(section.ToLower() == "property brokers" ? "selected" : "")>Property Brokers</option>*@
                        </select>
                    </div>

                    <div class="col-sm-6">
                        <label for="form-manager">Filter by Relationship Manager</label>
                        <select id="form-manager">
                            <option value="All">All</option>
                            @foreach (var item in model.Members)
                            {
                                <option value="@item.GetKey()">@item.Name</option>
                            }
                        </select>
                    </div>
                </div>
            </form>

            <div id="team-container">
                @Html.Partial("/Views/MainSurface/RenderTeamMembers.cshtml", model)
            </div>

        </div>

    </div>
</section>

@section scripts
{
    <script>
		$(function() {
			$('#form-type').change(function() {
				$.ajax({
					url: '@Url.Action("GetTeamMembers", "MainSurface")',
					data: JSON.stringify({ teamName: $('#form-type').val(), sectionNode: @Model.Content.TeamSection }),
					type: 'POST',
					contentType: "application/json; charset=utf-8",
					cache: false,
					success: function(data) {
						$('#form-manager').find('option').remove().end();

						$('#form-manager').append('<option values="All">All</option>');

						$(data).each(function(index) {
							$('#form-manager').append('<option value="' + data[index].Key + '">' + data[index].Name + '</option>');
						});

						renderTeamMembers();
					}
				});
			});

			$('#form-manager').change(renderTeamMembers);

			//$('#form-manager').change(function() {
			//	var id = $('#form-manager').val();
			//	$('.contact').each(function() {
			//		if (id === '') {
			//			$(this).hide();
			//		}
			//		if (id === 'All') {
			//			$(this).show();
			//		} else {
			//			if ($(this).data('memberid') === id) $(this).show();
			//			else $(this).hide();
			//		}
			//	});
			//});
		});

		function renderTeamMembers() {
			$.ajax({
				url: '@Url.Action("RenderTeamMembers", "MainSurface")',
                data: JSON.stringify({ teamName: $('#form-type').val(), memberName: $('#form-manager').val(), sectionNode: @Model.Content.TeamSection }),
				type: 'POST',
				contentType: "application/json; charset=utf-8",
				cache: false,
				success: function(data) {
					$('#team-container').html(data);
				}
			});
		}
    </script>

}

BankOfCyprusUK.Web/Views/OverdraftCalculator.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.OverdraftCalculator>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    var sectionLandingPage = Model.Content.AncestorOrSelf<SectionLandingPage>();
}

@Html.Partial("/Views/Partials/SectionNavigation.cshtml", sectionLandingPage)

@if (Model.Content.DisplayTagLine)
    {
        var homepage = Umbraco.TypedContentAtRoot().FirstOrDefault(x => x.DocumentTypeAlias == "homePage");
        var homePageTagLine = string.Empty;
        if (homepage != null)
        {
            homePageTagLine = homepage.GetPropertyValue<string>("tagLine");
        }
        var tagLine = !string.IsNullOrEmpty(Model.Content.TagLine) ? Model.Content.TagLine : homePageTagLine;
        <div class="tagline blue">
            <div class="container-fluid">
                <p>
                    @tagLine
                </p>
            </div>
        </div>
    }

    @if (Model.Content.PageHeader.Any())
    {
        @MvcHtmlString.Create(library.RenderTemplate(Model.Content.PageHeader.First().Id))
    }
    else if (Model.Content.Parent<SectionSubPage>() != null && Model.Content.Parent<SectionSubPage>().PageHeader != null && Model.Content.Parent<SectionSubPage>().PageHeader.Any())
    {
        @MvcHtmlString.Create(library.RenderTemplate(Model.Content.Parent<SectionSubPage>().PageHeader.First().Id))
    }

<section class="content-with-left-menu">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-8 col-sm-push-4">
                <div class="content">
                    <h2>@Model.Content.CalculatorHeading</h2>
                        @Model.Content.IntroText

                    <section id="calculator" class="overdraft-calc" role="calculator">
                        <div id="odCalculator" data-parsley-validate="">
                            <div class="calc">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="form-group">
                                            <h3>@Model.Content.GetPropertyValue("accountHeading")</h3>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                <div class="user-inputs card">
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label for="AMslider-value">Arranged overdraft amount</label>
                                            <div id="AM-slider"></div>
                                            <span class="pounds">£</span>
                                            <input id="AMslider-value" type="text" name="limit" required="" data-parsley-multiple-of="5" data-parsley-max="5000" data-parsley-trigger="change">
                                            <p class="form-note">Maximum amount £5,000</p>
                                        </div>
                                        <hr>
                                        <div class="form-group">
                                            <label for="odSlider-value">Amount you are overdrawn</label>
                                            <div id="odSlider"></div>
                                            <span class="pounds">£</span>
                                            <input id="odSlider-value" type="text" name="overdrawn" required="" data-parsley-multiple-of="5" data-parsley-max="5000" data-parsley-trigger="change">
                                            <p class="form-note">Maximum amount £5,000</p>
                                        </div>
                                        <hr>
                                        <div class="form-group">
                                            <label for="odDaysSlider-value">Number of days overdrawn</label>
                                            <div id="odDaysSlider"></div>
                                            <span class="days">days</span>
                                            <input id="odDaysSlider-value" value="1" min="1" max="31" step="1" />
                                            <p class="form-note">Between 1 and 31 days</p>
                                        </div>
                                        <hr>
                                        <div class="form-group">
                                            <button type="submit" id="calculate" class="button blue">Calculate your costs</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div id="results" class="calc-results" style="display:none">
                            @Html.Action("RenderOverdraftCalculatorResults", "MainSurface")
                        </div>
                    </section>

                    <section class="rep-example">
                        <div class="cut-out">
                            @Model.Content.RepresentativeExample
                        </div>
                        <div class="cut-out">
                            <div class="row">
                                <div class="col-sm-8">
                                    @Model.Content.ReprenentativeExampleSecondBlock
                                </div>
                                <div class="col-sm-4">
                                    <a href="@Umbraco.NiceUrl(Model.Content.ContactButtonLink.Id)" class="button blue float-right" target="_blank">
                                        @Model.Content.ButtonText   <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </section>

                    <h3>@Model.Content.BottomBlockTitle</h3>
                        @Model.Content.BottomBlock

                </div>
            </div>

            <div class="col-sm-4 col-sm-pull-8">
                <div class="side">
                        @Html.Partial("/Views/Partials/LeftNavigation.cshtml", Model.Content)
                        @if (!Model.Content.HideFscsbox)
                        {
                            @Html.Partial("/Views/Partials/fscs.cshtml")
                        }
                    </div>
            </div>
        </div>

    </div>
</section>

BankOfCyprusUK.Web/Views/OverdraftCalculatorApril.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.OverdraftCalculator>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    var sectionLandingPage = Model.Content.AncestorOrSelf<SectionLandingPage>();
}

@Html.Partial("/Views/Partials/SectionNavigation.cshtml", sectionLandingPage)

@if (Model.Content.DisplayTagLine)
{
    var homepage = Umbraco.TypedContentAtRoot().FirstOrDefault(x => x.DocumentTypeAlias == "homePage");
    var homePageTagLine = string.Empty;
    if (homepage != null)
    {
        homePageTagLine = homepage.GetPropertyValue<string>("tagLine");
    }
    var tagLine = !string.IsNullOrEmpty(Model.Content.TagLine) ? Model.Content.TagLine : homePageTagLine;
    <div class="tagline blue">
        <div class="container-fluid">
            <p>
                @tagLine
            </p>
        </div>
    </div>
}

@if (Model.Content.PageHeader.Any())
{
    @MvcHtmlString.Create(library.RenderTemplate(Model.Content.PageHeader.First().Id))
}
else if (Model.Content.Parent<SectionSubPage>() != null && Model.Content.Parent<SectionSubPage>().PageHeader != null && Model.Content.Parent<SectionSubPage>().PageHeader.Any())
{
    @MvcHtmlString.Create(library.RenderTemplate(Model.Content.Parent<SectionSubPage>().PageHeader.First().Id))
}


<section class="content-with-left-menu">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-8 col-sm-push-4">
                <div class="content">
                    <h2>@Model.Content.CalculatorHeading</h2>
                    @Model.Content.IntroText
                 
                    <section id="calculator" class="overdraft-calc" role="calculator">
                        <div id="odCalculator" data-parsley-validate="">
                            <div class="calc">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="form-group">
                                            <h3>@Model.Content.GetPropertyValue("accountHeading")</h3>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                <div class="user-inputs card">
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label for="AMslider-value">Arranged overdraft amount</label>
                                            <div id="AM-slider"></div>
                                            <span class="pounds">£</span>
                                            <input id="AMslider-value" type="text" name="limit" required="" data-parsley-multiple-of="5" data-parsley-max="5000" data-parsley-trigger="change">
                                            <p class="form-note">Maximum amount £5,000</p>
                                        </div>
                                        <hr>
                                        <div class="form-group">
                                            <label for="odSlider-value">Amount you are overdrawn</label>
                                            <div id="odSlider"></div>
                                            <span class="pounds">£</span>
                                            <input id="odSlider-value" type="text" name="overdrawn" required="" data-parsley-multiple-of="5" data-parsley-max="5000" data-parsley-trigger="change">
                                            <p class="form-note">Maximum amount £5,000</p>
                                        </div>
                                        <hr>
                                        <div class="form-group">
                                            <label for="odDaysSlider-value">Number of days overdrawn</label>
                                            <div id="odDaysSlider"></div>
                                            <span class="days">days</span>
                                            <input id="odDaysSlider-value" value="1" min="1" max="31" step="1" />
                                            <p class="form-note">Between 1 and 31 days</p>
                                        </div>
                                        <hr>
                                        <div class="form-group">
                                            <button type="submit" id="calculateApril" class="button blue">Calculate your costs</button>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>
                    
                        <div id="results" class="calc-results" style="display:none">
                            @Html.Action("RenderOverdraftCalculatorResults", "MainSurface")
                        </div>

                    </section>
                  
                    <section class="rep-example">
                        <div class="cut-out">
                            @Model.Content.GetPropertyValue("representativeExample")
                        </div>
                        <div class="cut-out">
                            <div class="row">
                                <div class="col-sm-8">
                                   @Model.Content.GetPropertyValue("representativeExampleSecondBlock")
                                </div>
                                <div class="col-sm-4">
                                    <a href="/contact/" class="button blue float-right" target="_self">
                                        Contact Us <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </section>

                    <h3>@Model.Content.BottomBlockTitle</h3>
                    @Model.Content.BottomBlock
               
                </div>
            </div>

            <div class="col-sm-4 col-sm-pull-8">
                <div class="side">
                    @Html.Partial("/Views/Partials/LeftNavigation.cshtml", Model.Content)
                    @if (!Model.Content.HideFscsbox)
                    {
                        @Html.Partial("/Views/Partials/fscs.cshtml")
                    }
                </div>
            </div>
        </div>

    </div>
</section>
                